name: 🐍 Gerar Cobra

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Gerar Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Gisely-dev
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Publicar Snake
        run: |
          cp -r dist /tmp/snake-dist

          git checkout --orphan output

          git rm -rf . || true
          git clean -fdx

          cp -r /tmp/snake-dist/* .

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "Update Snake"
          git push origin output --force
