name: Generate Snake

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Gisely-dev
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Publish Snake
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          cd dist
          git init
          git add .
          git commit -m "Update Snake"

          git branch -M output
          git remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/Gisely-dev/Gisely-dev.git"
          git push --force origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
